KobeTown/Models/EFcodeFirts/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KobeTown.Models.EFcodeFirts
{
    [Table("tb_ProductCategory")]
    public class ProductCategory : CommonAbstract
    {
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(150)] 
        public string Title { get; set; }
        [Required]
        [StringLength(150)]
        public string Alias { get; set; }

        public string Description { get; set; }

        [StringLength(250)]
        public string Icon { get; set; }

        public ICollection<Product> Products { get; set; }
    }
}

KobeTown/Areas/Admin/Controllers/ProductCategoryController.cs
using KobeTown.Models;
using KobeTown.Models.EFcodeFirts;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KobeTown.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductCategoryController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/ProductCategory
        public ActionResult Index()
        {
            var items = db.ProductCategories.ToList();
            return View(items);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductCategory model)
        {
            if(ModelState.IsValid)
            {
                model.CreatedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;
                model.Alias = KobeTown.Models.Common.Filter.FilterChar(model.Title);
                db.ProductCategories.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Edit (int id)
        {
            var item = db.ProductCategories.Find(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCategory model)
        {
            if (ModelState.IsValid)
            {
                db.ProductCategories.Attach(model);
                model.ModifiedDate = DateTime.Now;
                model.Alias = KobeTown.Models.Common.Filter.FilterChar(model.Title);
                db.Entry(model).Property(x => x.Title).IsModified = true;
                db.Entry(model).Property(x => x.Description).IsModified = true;
                db.Entry(model).Property(x => x.Alias).IsModified = true;
                db.Entry(model).Property(x => x.Icon).IsModified = true;
                db.Entry(model).Property(x => x.ModifiedDate).IsModified = true;
                db.Entry(model).Property(x => x.ModifiedBy).IsModified = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = db.ProductCategories.Find(id);
            if(item != null)
            {
                //var DeleteItem = db.ProductCategories.Attach(item);
                db.ProductCategories.Remove(item);
                db.SaveChanges();
                return Json(new { success = true });
            }   
            return Json( new { success = false });
        }
    }
}

KobeTown/Areas/Admin/Views/ProductCategory/Create.cshtml
@model KobeTown.Models.EFcodeFirts.ProductCategory
@{
    ViewBag.Title = "Thêm mới danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<style>
    .page-header {
        margin: -10px;
        padding-bottom: -5px;
    }

    .card-body {
        padding: 5px 20px 20px 20px;
    }
</style>

<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">Quản Lý Danh Mục Sản Phẩm</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/Admin/Product/Index">Danh Mục Sản phẩm</a></li>
                <li class="breadcrumb-item active" aria-current="page">Thêm Mới</li>
            </ol>
        </nav>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="card-header">
                    <h4 class="card-title">Thêm mới danh mục sản phẩm</h4>
                </div>
                @using (Html.BeginForm("Create", "ProductCategory", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)

                    <div class="card">
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="active tab-pane" id="activity">
                                    <div class="form-group">
                                        <label for="exampleIputEmail1">Tiêu đề</label>
                                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Tiêu đề" })
                                        @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleIputEmail1">Mô tả</label>
                                        @Html.TextBoxFor(x => x.Description, new { @class = "form-control", @placeholder = "Mô tả" })
                                        @Html.ValidationMessageFor(x => x.Description, null, new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleIputEmail1">Icon</label>
                                        @Html.TextBoxFor(x => x.Icon, new { @class = "form-control", @placeholder = "Hình ảnh" })
                                        @Html.ValidationMessageFor(x => x.Icon, null, new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleIputEmail1">Alias</label>
                                        @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Alias" })
                                        @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <a href="/Admin/ProductCategory" class="btn btn-danger">Quay lại</a>
                                        <button type="submit" class="btn btn-primary">Lưu</button>

                                    </div>
                                </div>
                                
                            </div>

                        </div>

                      
                        <div>
                           
                        </div>
                    </div>

                }

            </div>
        </div>
 </div>

KobeTown/Areas/Admin/Views/ProductCategory/Edit.cshtml
@model KobeTown.Models.EFcodeFirts.ProductCategory
@{
    ViewBag.Title = "Cập nhật danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<style>
    .page-header {
        margin: -10px;
        padding-bottom: -5px;
    }

    .card-body {
        padding: 5px 20px 20px 20px;
    }
</style>

<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">Quản Lý Danh Mục Sản Phẩm</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/Admin/Product/Index">Danh Mục Sản Phẩm</a></li>
                <li class="breadcrumb-item active" aria-current="page">Cập Nhật</li>
            </ol>
        </nav>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="card-header">
                    <h4 class="card-title">Cập nhật danh mục sản phẩm</h4>
                </div>
                @using (Html.BeginForm("Edit", "ProductCategory", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(x => x.Id)
                    <div class="card">
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="active tab-pane" id="activity">
                                    <div class="form-group">
                                        <label for="exampleIputEmail1">Tiêu đề</label>
                                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Tiêu đề" })
                                        @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleIputEmail1">Mô tả</label>
                                        @Html.TextBoxFor(x => x.Description, new { @class = "form-control", @placeholder = "Mô tả" })
                                        @Html.ValidationMessageFor(x => x.Description, null, new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleIputEmail1">Icon</label>
                                        @Html.TextBoxFor(x => x.Icon, new { @class = "form-control", @placeholder = "Hình ảnh" })
                                        @Html.ValidationMessageFor(x => x.Icon, null, new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleIputEmail1">Alias</label>
                                        @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Alias" })
                                        @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <a href="/Admin/ProductCategory" class="btn btn-danger">Quay lại</a>
                                        <button type="submit" class="btn btn-primary">Lưu</button>

                                    </div>
                                </div>

                            </div>

                        </div>


                        <div>

                        </div>
                    </div>

                }

            </div>
        </div>
    </div>
</div>

KobeTown/Areas/Admin/Views/ProductCategory/Index.cshtml
@model IEnumerable<KobeTown.Models.EFcodeFirts.ProductCategory>
@{
    ViewBag.Title = "Danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<style>
    .page-header {
        margin: -10px;
        padding-bottom: -5px;
    }

    .card-body {
        padding: 5px 20px 20px 20px;
    }
</style>
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">Quản Lý Danh Mục Sản Phẩm</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Danh Mục Sản Phẩm</li>
            </ol>
        </nav>

    </div>
    <div class="card-body">
        <div class="header-right d-flex flex-wrap mt-2 mt-sm-0">
            <h4 class="card-title">Danh sách danh mục sản phẩm</h4>
            <div class="card-tools ml-auto align-self-center">
                <a href="/Admin/ProductCategory/Create" class=" btn btn-primary">Thêm mới</a>
                <a href="#" class=" btn btn-danger" id="btnDeleteAll">Xóa</a>
            </div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            @*<th><input type="checkbox" id="SelectAll" /></th>*@
                            <th>STT</th>
                            <th>Tiêu đề</th>
                            <th>Alias</th>
                            <th>Mô tả</th>
                            <th>Ngày tạo</th>
                            <th>Ngày sửa</th>
                            @*<th>Hiển thị</th>*@

                            <th style="width:150px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Any())
                        {
                            var i = 1;
                            foreach (var item in Model)
                            {
                                <tr id="trow_@item.Id">
                                    @*<td><input type="checkbox" class="cbkItem" value="@item.Id" /></td>*@
                                    <td>@i</td>
                                    <td>@item.Title</td>
                                    <td>@item.Alias</td>
                                    <td>@item.Description</td>
                                    <td>@item.CreatedDate.ToString("dd/MM/yyyy")</td>
                                    <td>@item.ModifiedDate.ToString("dd/MM/yyyy")</td>
                                    <td class="text-center">
                                        <a href="/admin/productcategory/edit/@item.Id" data-id="@item.Id" class="btn btn-sm btn-primary">Sửa</a>
                                        <a href="#" data-id="@item.Id" class="btn btn-sm btn-danger btnDelete">Xóa</a>
                                    </td>
                                </tr>
                                i++;
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="4">Không có bản ghi nào!!!</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <!-- content-wrapper ends -->
    </div>

</div>
@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '#btnDeleteAll', function (e) {
                e.prevenDefault();
                var str = "";
                var ckeckbox = $(this).parents('.card').find('tr td input:checkbox');
                var i = 0;
                checkbox.each(function () {
                    if (this.checked) {
                        var _id = $(this).val();
                        if (i === 0) {
                            str += _id;
                        } else {
                            str += "," + _id;
                        }
                        i++;
                    } else {
                        ckeckbox.attr('selected', '');
                    }
                });
                if (str.length > 0) {
                    var conf = confirm('Bạn có muốn xóa bản ghi này không?');
                    if (conf === true) {
                        $.ajax({
                            url: 'Admin/ProductCategory/deleteAll',
                            type: 'POST',
                            data: { ids: str },
                            success: function (rs) {
                                if (rs.success) {
                                    location.reload();
                                }
                            }
                        });
                    }
                }
            });
            $('body').on('change', '#SelectAll', function () {
                var checkStatus = this.checked;
                var checkbox = $(this).parents('.card-body').find('tr td input:checkbox');
                checkbox.each(function () {
                    this.checked = checkStatus;
                    if (this.checked) {
                        checkbox.attr('selected', 'checked');
                    } else {
                        checkbox.attr('selected', '');
                    }
                });
            })
            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm('Bạn có muốn xóa bản ghi này không');
                if (conf === true) {
                    $.ajax({
                        url: '/Admin/ProductCategory/Delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    })
                }
            });
            $('body').on('click', '.btnActive', function (e) {
                e.prevenDefault();
                var btn = $(this);
                var id = btn.data("id");
                $.ajax({
                    url: '/Admin/Products/IsActive',
                    type: 'POST',
                    data: { id: id },
                    success: function (rs) {
                        if (rs.success) {
                            if (rs.isActive) {
                                btn.html("<i class='fa fa-check text-success'></i>");
                            } else {
                                btn.html("<i class='fas fa-times text-danger'></i>");
                            }
                        }
                    }
                })
            })
        });
    </script>
}




@*@section scripts{
        <script>
            $(document).ready(function () {
                $('body').on('click', '.btnDeleteAll', function (e) {
                    e.prevenDefault();
                    var str = "";
                    var ckeckbox = $(this).parents('.card').find('tr td input:checkbox');
                    var i = 0;
                    checkbox.each(function () {
                        if (this.checked) {
                            var _id = $(this).val();
                            if (i === 0) {
                                str += _id;
                            } else {
                                str += "," + _id;
                            }
                            i++;
                        } else {
                            ckeckbox.attr('selected', '');
                        }
                    });
                    if (str.length > 0) {
                        var conf = confirm('Bạn có muốn xóa bản ghi này không?');
                        if (conf === true) {
                            $.ajax({
                                url: 'Admin/ProductCategory/deleteAll',
                                type: 'POST',
                                data: { ids: str },
                                success: function (rs) {
                                    if (rs.success) {
                                        location.reload();
                                    }
                                }
                            });
                        }
                    }
                });
                $('body').on('change', '#SelectAll', function () {
                    var checkStatus
                })
            })
        </script>
    }*@